services:
  rdb-master:
    image: bitnami/postgresql:latest
    container_name: rdb-master
    restart: always
    env_file:
      - master.env
    ports:
      - '5432:5432' # Expose PostgreSQL port
    volumes:
      - rdb-master-data:/bitnami/postgresql # Persist database data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 30s
      timeout: 5s
      retries: 3

  rdb-replica:
    image: bitnami/postgresql:latest
    container_name: rdb-replica
    depends_on:
      rdb-master:
        condition: service_healthy
    restart: always
    env_file:
      - replica.env
    ports:
      - '5433:5432' # Expose replica on a different port
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 30s
      timeout: 5s
      retries: 3

  rdb-shadow:
    image: bitnami/postgresql:latest
    container_name: rdb-shadow
    depends_on:
      rdb-master:
        condition: service_healthy
    restart: always
    env_file:
      - shadow.env
    ports:
      - "5434:5432"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-user}"]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6378:6379"
    command: sh -c "redis-server --requirepass $$REDIS_PASSWORD --appendonly yes"
    env_file:
      - docker.env
    volumes:
      - redis-data:/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3

  api:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    container_name: api
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - '3000:3000'
    depends_on:
      rdb-master:
        condition: service_healthy # Wait until relational db is fully ready
      redis:
        condition: service_healthy # Wait until redis is fully ready
    networks:
      - app-network

volumes: # Volume to persist database data
  rdb-master-data:
  redis-data:
    driver: local

networks:
  app-network: # Network to connect the API and database containers
    driver: bridge
